# Site settings
baseURL = "https://docs.violinist.io/"
languageCode = "en-us"
title = "Violinist documentation"
theme = "hugo-simpledoc-theme"
pygmentsStyle = "manni"
publishDir = "docs"
[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  smartlists = true
  extensions = ["hardLineBreak"]

# Site parameters
[params]

    # Meta
    description = "Violinist documentation"
    author = "support@violinist.io"
    keywords = "composer, violinist, php, documentation"
    
    # Header
    # If not set, site title and meta description will be shown.
    # You may use markdown here
    headerTitle = "Violinist documentation"
    completeExample = """
```
{
  "name": "company/project",
  "description": "My awesome project",
  "dependencies": {
    "vendor/package": "~1.0.0",
  },
  "extra": {
    "violinist": {
      "allow_updates_beyond_constraint": 1,
      "blacklist: [],
      "update_with_dependencies": 1
    }
  }
}
```
"""
    
    # Back-to-top button name
    bttButton = ""
